# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Api.EnterpriseTeamOrganizations do
  @moduledoc """
  GitHub `enterprise-team-organizations` API.
  """
  import Noizu.Github

  @doc """
  Add an organization assignment

  @see https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#add-an-organization-assignment
  """
  def add(enterprise, enterprise_team, org, body, options \\ nil) do
    url =
      github_base() <> "/enterprises/#{enterprise}/teams/#{enterprise_team}/organizations/#{org}"

    body = body
    api_call(:put, url, body, Noizu.Github.OrganizationSimple, options)
  end

  @doc """
  Add organization assignments

  @see https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#add-organization-assignments
  """
  def bulk_add(enterprise, enterprise_team, body, options \\ nil) do
    url = github_base() <> "/enterprises/#{enterprise}/teams/#{enterprise_team}/organizations/add"
    body = body
    api_call(:post, url, body, Noizu.Github.Collection.OrganizationSimple, options)
  end

  @doc """
  Remove organization assignments

  @see https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#remove-organization-assignments
  """
  def bulk_remove(enterprise, enterprise_team, body, options \\ nil) do
    url =
      github_base() <> "/enterprises/#{enterprise}/teams/#{enterprise_team}/organizations/remove"

    body = body
    api_call(:post, url, body, Noizu.Github.Raw, options)
  end

  @doc """
  Delete an organization assignment

  @see https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#delete-an-organization-assignment
  """
  def delete(enterprise, enterprise_team, org, options \\ nil) do
    url =
      github_base() <> "/enterprises/#{enterprise}/teams/#{enterprise_team}/organizations/#{org}"

    body = %{}
    api_call(:delete, url, body, Noizu.Github.Raw, options)
  end

  @doc """
  Get organization assignment

  @see https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#get-organization-assignment
  """
  def get_assignment(enterprise, enterprise_team, org, options \\ nil) do
    url =
      github_base() <> "/enterprises/#{enterprise}/teams/#{enterprise_team}/organizations/#{org}"

    body = %{}
    api_call(:get, url, body, Noizu.Github.OrganizationSimple, options)
  end

  @doc """
  Get organization assignments

  @see https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#get-organization-assignments
  """
  def get_assignments(enterprise, enterprise_team, options \\ nil) do
    url =
      (
        query =
          [
            get_field(:per_page, options, nil),
            get_field(:page, options, nil)
          ]
          |> Enum.filter(& &1)

        qs = if query == [], do: "", else: "?" <> Enum.join(query, "&")
        github_base() <> "/enterprises/#{enterprise}/teams/#{enterprise_team}/organizations" <> qs
      )

    body = %{}
    api_call(:get, url, body, Noizu.Github.Collection.OrganizationSimple, options)
  end
end
