# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Api.Gitignore do
  @moduledoc """
  GitHub `gitignore` API.
  """
  import Noizu.Github

  @doc """
  Get all gitignore templates

  @see https://docs.github.com/rest/gitignore/gitignore#get-all-gitignore-templates
  """
  def get_all_templates(options \\ nil) do
    url = github_base() <> "/gitignore/templates"
    body = %{}
    api_call(:get, url, body, Noizu.Github.Collection, options)
  end

  @doc """
  Get a gitignore template

  @see https://docs.github.com/rest/gitignore/gitignore#get-a-gitignore-template
  """
  def get_template(name, options \\ nil) do
    url = github_base() <> "/gitignore/templates/#{name}"
    body = %{}
    api_call(:get, url, body, Noizu.Github.GitignoreTemplate, options)
  end
end
