# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Api.Emojis do
  @moduledoc """
  GitHub `emojis` API.
  """
  import Noizu.Github

  @doc """
  Get emojis

  @see https://docs.github.com/rest/emojis/emojis#get-emojis
  """
  def get(options \\ nil) do
    url = github_base() <> "/emojis"
    body = %{}
    api_call(:get, url, body, Noizu.Github.Raw, options)
  end
end
