# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Api.Markdown do
  @moduledoc """
  GitHub `markdown` API.
  """
  import Noizu.Github

  @doc """
  Render a Markdown document

  @see https://docs.github.com/rest/markdown/markdown#render-a-markdown-document
  """
  def render(body, options \\ nil) do
    url = github_base() <> "/markdown"
    body = body
    api_call(:post, url, body, Noizu.Github.Raw, options)
  end

  @doc """
  Render a Markdown document in raw mode

  @see https://docs.github.com/rest/markdown/markdown#render-a-markdown-document-in-raw-mode
  """
  def render_raw(body, options \\ nil) do
    url = github_base() <> "/markdown/raw"
    body = body
    api_call(:post, url, body, Noizu.Github.Raw, options)
  end
end
