# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsHostedRunnerCuratedImage do
  @moduledoc false
  defstruct [
    :display_name,
    :id,
    :platform,
    :size_gb,
    :source
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      display_name: Map.get(json, :display_name),
      id: Map.get(json, :id),
      platform: Map.get(json, :platform),
      size_gb: Map.get(json, :size_gb),
      source: Map.get(json, :source)
    }
  end

  def from_json(other, _headers), do: other
end
