# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsCacheList do
  @moduledoc false
  defstruct [
    :actions_caches,
    :total_count
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      actions_caches: Map.get(json, :actions_caches),
      total_count: Map.get(json, :total_count)
    }
  end

  def from_json(other, _headers), do: other
end
