# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsHostedRunnerCustomImageVersion do
  @moduledoc false
  defstruct [
    :created_on,
    :size_gb,
    :state,
    :state_details,
    :version
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_on: Map.get(json, :created_on),
      size_gb: Map.get(json, :size_gb),
      state: Map.get(json, :state),
      state_details: Map.get(json, :state_details),
      version: Map.get(json, :version)
    }
  end

  def from_json(other, _headers), do: other
end
