# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsGetDefaultWorkflowPermissions do
  @moduledoc false
  defstruct [
    :can_approve_pull_request_reviews,
    :default_workflow_permissions
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      can_approve_pull_request_reviews: Map.get(json, :can_approve_pull_request_reviews),
      default_workflow_permissions: Map.get(json, :default_workflow_permissions)
    }
  end

  def from_json(other, _headers), do: other
end
