# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsPublicKey do
  @moduledoc false
  defstruct [
    :created_at,
    :id,
    :key,
    :key_id,
    :title,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      id: Map.get(json, :id),
      key: Map.get(json, :key),
      key_id: Map.get(json, :key_id),
      title: Map.get(json, :title),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
