# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsRepositoryPermissions do
  @moduledoc false
  defstruct [
    :allowed_actions,
    :enabled,
    :selected_actions_url,
    :sha_pinning_required
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      allowed_actions: Map.get(json, :allowed_actions),
      enabled: Map.get(json, :enabled),
      selected_actions_url: Map.get(json, :selected_actions_url),
      sha_pinning_required: Map.get(json, :sha_pinning_required)
    }
  end

  def from_json(other, _headers), do: other
end
