# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsHostedRunnerMachineSpec do
  @moduledoc false
  defstruct [
    :cpu_cores,
    :id,
    :memory_gb,
    :storage_gb
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      cpu_cores: Map.get(json, :cpu_cores),
      id: Map.get(json, :id),
      memory_gb: Map.get(json, :memory_gb),
      storage_gb: Map.get(json, :storage_gb)
    }
  end

  def from_json(other, _headers), do: other
end
