# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsHostedRunner do
  @moduledoc false
  defstruct [
    :id,
    :image_details,
    :image_gen,
    :last_active_on,
    :machine_size_details,
    :maximum_runners,
    :name,
    :platform,
    :public_ip_enabled,
    :public_ips,
    :runner_group_id,
    :status
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      id: Map.get(json, :id),
      image_details:
        Noizu.Github.NullableActionsHostedRunnerPoolImage.from_json(Map.get(json, :image_details)),
      image_gen: Map.get(json, :image_gen),
      last_active_on: Map.get(json, :last_active_on),
      machine_size_details:
        Noizu.Github.ActionsHostedRunnerMachineSpec.from_json(
          Map.get(json, :machine_size_details)
        ),
      maximum_runners: Map.get(json, :maximum_runners),
      name: Map.get(json, :name),
      platform: Map.get(json, :platform),
      public_ip_enabled: Map.get(json, :public_ip_enabled),
      public_ips:
        Enum.map(Map.get(json, :public_ips) || [], &Noizu.Github.PublicIp.from_json(&1)),
      runner_group_id: Map.get(json, :runner_group_id),
      status: Map.get(json, :status)
    }
  end

  def from_json(other, _headers), do: other
end
