# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ActionsCacheUsageByRepository do
  @moduledoc false
  defstruct [
    :active_caches_count,
    :active_caches_size_in_bytes,
    :full_name
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      active_caches_count: Map.get(json, :active_caches_count),
      active_caches_size_in_bytes: Map.get(json, :active_caches_size_in_bytes),
      full_name: Map.get(json, :full_name)
    }
  end

  def from_json(other, _headers), do: other
end
