# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Actor do
  @moduledoc false
  defstruct [
    :avatar_url,
    :display_login,
    :gravatar_id,
    :id,
    :login,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      avatar_url: Map.get(json, :avatar_url),
      display_login: Map.get(json, :display_login),
      gravatar_id: Map.get(json, :gravatar_id),
      id: Map.get(json, :id),
      login: Map.get(json, :login),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
