# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.AppPermissions do
  @moduledoc false
  defstruct [
    :actions,
    :administration,
    :artifact_metadata,
    :attestations,
    :checks,
    :code_quality,
    :codespaces,
    :contents,
    :custom_properties_for_organizations,
    :dependabot_secrets,
    :deployments,
    :discussions,
    :email_addresses,
    :enterprise_custom_properties_for_organizations,
    :environments,
    :followers,
    :git_ssh_keys,
    :gpg_keys,
    :interaction_limits,
    :issues,
    :members,
    :merge_queues,
    :metadata,
    :organization_administration,
    :organization_announcement_banners,
    :organization_copilot_agent_settings,
    :organization_copilot_seat_management,
    :organization_custom_org_roles,
    :organization_custom_properties,
    :organization_custom_roles,
    :organization_events,
    :organization_hooks,
    :organization_packages,
    :organization_personal_access_token_requests,
    :organization_personal_access_tokens,
    :organization_plan,
    :organization_projects,
    :organization_secrets,
    :organization_self_hosted_runners,
    :organization_user_blocking,
    :packages,
    :pages,
    :profile,
    :pull_requests,
    :repository_custom_properties,
    :repository_hooks,
    :repository_projects,
    :secret_scanning_alerts,
    :secrets,
    :security_events,
    :single_file,
    :starring,
    :statuses,
    :vulnerability_alerts,
    :workflows
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      actions: Map.get(json, :actions),
      administration: Map.get(json, :administration),
      artifact_metadata: Map.get(json, :artifact_metadata),
      attestations: Map.get(json, :attestations),
      checks: Map.get(json, :checks),
      code_quality: Map.get(json, :code_quality),
      codespaces: Map.get(json, :codespaces),
      contents: Map.get(json, :contents),
      custom_properties_for_organizations: Map.get(json, :custom_properties_for_organizations),
      dependabot_secrets: Map.get(json, :dependabot_secrets),
      deployments: Map.get(json, :deployments),
      discussions: Map.get(json, :discussions),
      email_addresses: Map.get(json, :email_addresses),
      enterprise_custom_properties_for_organizations:
        Map.get(json, :enterprise_custom_properties_for_organizations),
      environments: Map.get(json, :environments),
      followers: Map.get(json, :followers),
      git_ssh_keys: Map.get(json, :git_ssh_keys),
      gpg_keys: Map.get(json, :gpg_keys),
      interaction_limits: Map.get(json, :interaction_limits),
      issues: Map.get(json, :issues),
      members: Map.get(json, :members),
      merge_queues: Map.get(json, :merge_queues),
      metadata: Map.get(json, :metadata),
      organization_administration: Map.get(json, :organization_administration),
      organization_announcement_banners: Map.get(json, :organization_announcement_banners),
      organization_copilot_agent_settings: Map.get(json, :organization_copilot_agent_settings),
      organization_copilot_seat_management: Map.get(json, :organization_copilot_seat_management),
      organization_custom_org_roles: Map.get(json, :organization_custom_org_roles),
      organization_custom_properties: Map.get(json, :organization_custom_properties),
      organization_custom_roles: Map.get(json, :organization_custom_roles),
      organization_events: Map.get(json, :organization_events),
      organization_hooks: Map.get(json, :organization_hooks),
      organization_packages: Map.get(json, :organization_packages),
      organization_personal_access_token_requests:
        Map.get(json, :organization_personal_access_token_requests),
      organization_personal_access_tokens: Map.get(json, :organization_personal_access_tokens),
      organization_plan: Map.get(json, :organization_plan),
      organization_projects: Map.get(json, :organization_projects),
      organization_secrets: Map.get(json, :organization_secrets),
      organization_self_hosted_runners: Map.get(json, :organization_self_hosted_runners),
      organization_user_blocking: Map.get(json, :organization_user_blocking),
      packages: Map.get(json, :packages),
      pages: Map.get(json, :pages),
      profile: Map.get(json, :profile),
      pull_requests: Map.get(json, :pull_requests),
      repository_custom_properties: Map.get(json, :repository_custom_properties),
      repository_hooks: Map.get(json, :repository_hooks),
      repository_projects: Map.get(json, :repository_projects),
      secret_scanning_alerts: Map.get(json, :secret_scanning_alerts),
      secrets: Map.get(json, :secrets),
      security_events: Map.get(json, :security_events),
      single_file: Map.get(json, :single_file),
      starring: Map.get(json, :starring),
      statuses: Map.get(json, :statuses),
      vulnerability_alerts: Map.get(json, :vulnerability_alerts),
      workflows: Map.get(json, :workflows)
    }
  end

  def from_json(other, _headers), do: other
end
