# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ArtifactDeploymentRecord do
  @moduledoc false
  defstruct [
    :attestation_id,
    :cluster,
    :created_at,
    :deployment_name,
    :digest,
    :id,
    :logical_environment,
    :physical_environment,
    :runtime_risks,
    :tags,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      attestation_id: Map.get(json, :attestation_id),
      cluster: Map.get(json, :cluster),
      created_at: Map.get(json, :created_at),
      deployment_name: Map.get(json, :deployment_name),
      digest: Map.get(json, :digest),
      id: Map.get(json, :id),
      logical_environment: Map.get(json, :logical_environment),
      physical_environment: Map.get(json, :physical_environment),
      runtime_risks: Map.get(json, :runtime_risks),
      tags: Map.get(json, :tags),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
