# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Autolink do
  @moduledoc false
  defstruct [
    :id,
    :is_alphanumeric,
    :key_prefix,
    :updated_at,
    :url_template
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      id: Map.get(json, :id),
      is_alphanumeric: Map.get(json, :is_alphanumeric),
      key_prefix: Map.get(json, :key_prefix),
      updated_at: Map.get(json, :updated_at),
      url_template: Map.get(json, :url_template)
    }
  end

  def from_json(other, _headers), do: other
end
