# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.BillingUsageSummaryReportUser do
  @moduledoc false
  defstruct [
    :product,
    :repository,
    :sku,
    :timePeriod,
    :usageItems,
    :user
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      product: Map.get(json, :product),
      repository: Map.get(json, :repository),
      sku: Map.get(json, :sku),
      timePeriod: Map.get(json, :timePeriod),
      usageItems: Map.get(json, :usageItems),
      user: Map.get(json, :user)
    }
  end

  def from_json(other, _headers), do: other
end
