# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Blob do
  @moduledoc false
  defstruct [
    :content,
    :encoding,
    :highlighted_content,
    :node_id,
    :sha,
    :size,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      content: Map.get(json, :content),
      encoding: Map.get(json, :encoding),
      highlighted_content: Map.get(json, :highlighted_content),
      node_id: Map.get(json, :node_id),
      sha: Map.get(json, :sha),
      size: Map.get(json, :size),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
