# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.BranchRestrictionPolicy do
  @moduledoc false
  defstruct [
    :apps,
    :apps_url,
    :teams,
    :teams_url,
    :url,
    :users,
    :users_url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      apps: Map.get(json, :apps),
      apps_url: Map.get(json, :apps_url),
      teams: Enum.map(Map.get(json, :teams) || [], &Noizu.Github.Team.from_json(&1)),
      teams_url: Map.get(json, :teams_url),
      url: Map.get(json, :url),
      users: Map.get(json, :users),
      users_url: Map.get(json, :users_url)
    }
  end

  def from_json(other, _headers), do: other
end
