# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Budget do
  @moduledoc false
  defstruct [
    :budget_alerting,
    :budget_amount,
    :budget_entity_name,
    :budget_product_sku,
    :budget_scope,
    :budget_type,
    :id,
    :prevent_further_usage,
    :user
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      budget_alerting: Map.get(json, :budget_alerting),
      budget_amount: Map.get(json, :budget_amount),
      budget_entity_name: Map.get(json, :budget_entity_name),
      budget_product_sku: Map.get(json, :budget_product_sku),
      budget_scope: Map.get(json, :budget_scope),
      budget_type: Map.get(json, :budget_type),
      id: Map.get(json, :id),
      prevent_further_usage: Map.get(json, :prevent_further_usage),
      user: Map.get(json, :user)
    }
  end

  def from_json(other, _headers), do: other
end
