# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ClassroomAssignmentGrade do
  @moduledoc false
  defstruct [
    :assignment_name,
    :assignment_url,
    :github_username,
    :group_name,
    :points_available,
    :points_awarded,
    :roster_identifier,
    :starter_code_url,
    :student_repository_name,
    :student_repository_url,
    :submission_timestamp
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      assignment_name: Map.get(json, :assignment_name),
      assignment_url: Map.get(json, :assignment_url),
      github_username: Map.get(json, :github_username),
      group_name: Map.get(json, :group_name),
      points_available: Map.get(json, :points_available),
      points_awarded: Map.get(json, :points_awarded),
      roster_identifier: Map.get(json, :roster_identifier),
      starter_code_url: Map.get(json, :starter_code_url),
      student_repository_name: Map.get(json, :student_repository_name),
      student_repository_url: Map.get(json, :student_repository_url),
      submission_timestamp: Map.get(json, :submission_timestamp)
    }
  end

  def from_json(other, _headers), do: other
end
