# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ClassroomAcceptedAssignment do
  @moduledoc false
  defstruct [
    :assignment,
    :commit_count,
    :grade,
    :id,
    :passing,
    :repository,
    :students,
    :submitted
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      assignment: Noizu.Github.SimpleClassroomAssignment.from_json(Map.get(json, :assignment)),
      commit_count: Map.get(json, :commit_count),
      grade: Map.get(json, :grade),
      id: Map.get(json, :id),
      passing: Map.get(json, :passing),
      repository: Noizu.Github.SimpleClassroomRepository.from_json(Map.get(json, :repository)),
      students:
        Enum.map(Map.get(json, :students) || [], &Noizu.Github.SimpleClassroomUser.from_json(&1)),
      submitted: Map.get(json, :submitted)
    }
  end

  def from_json(other, _headers), do: other
end
