# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeScanningVariantAnalysisRepository do
  @moduledoc false
  defstruct [
    :full_name,
    :id,
    :name,
    :private,
    :stargazers_count,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      full_name: Map.get(json, :full_name),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      private: Map.get(json, :private),
      stargazers_count: Map.get(json, :stargazers_count),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
