# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeScanningAlertRule do
  @moduledoc false
  defstruct [
    :description,
    :full_description,
    :help,
    :help_uri,
    :id,
    :name,
    :security_severity_level,
    :severity,
    :tags
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      description: Map.get(json, :description),
      full_description: Map.get(json, :full_description),
      help: Map.get(json, :help),
      help_uri: Map.get(json, :help_uri),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      security_severity_level: Map.get(json, :security_severity_level),
      severity: Map.get(json, :severity),
      tags: Map.get(json, :tags)
    }
  end

  def from_json(other, _headers), do: other
end
