# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeOfConduct do
  @moduledoc false
  defstruct [
    :body,
    :html_url,
    :key,
    :name,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      body: Map.get(json, :body),
      html_url: Map.get(json, :html_url),
      key: Map.get(json, :key),
      name: Map.get(json, :name),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
