# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeScanningAnalysisDeletion do
  @moduledoc false
  defstruct [
    :confirm_delete_url,
    :next_analysis_url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      confirm_delete_url: Map.get(json, :confirm_delete_url),
      next_analysis_url: Map.get(json, :next_analysis_url)
    }
  end

  def from_json(other, _headers), do: other
end
