# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeQualitySetupUpdate do
  @moduledoc false
  defstruct [
    :languages,
    :runner_label,
    :runner_type,
    :state
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      languages: Map.get(json, :languages),
      runner_label: Map.get(json, :runner_label),
      runner_type: Map.get(json, :runner_type),
      state: Map.get(json, :state)
    }
  end

  def from_json(other, _headers), do: other
end
