# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeSecurityConfiguration do
  @moduledoc false
  defstruct [
    :advanced_security,
    :code_scanning_default_setup,
    :code_scanning_default_setup_options,
    :code_scanning_delegated_alert_dismissal,
    :code_scanning_options,
    :created_at,
    :dependabot_alerts,
    :dependabot_delegated_alert_dismissal,
    :dependabot_security_updates,
    :dependency_graph,
    :dependency_graph_autosubmit_action,
    :dependency_graph_autosubmit_action_options,
    :description,
    :enforcement,
    :html_url,
    :id,
    :name,
    :private_vulnerability_reporting,
    :secret_scanning,
    :secret_scanning_delegated_alert_dismissal,
    :secret_scanning_delegated_bypass,
    :secret_scanning_delegated_bypass_options,
    :secret_scanning_extended_metadata,
    :secret_scanning_generic_secrets,
    :secret_scanning_non_provider_patterns,
    :secret_scanning_push_protection,
    :secret_scanning_validity_checks,
    :target_type,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      advanced_security: Map.get(json, :advanced_security),
      code_scanning_default_setup: Map.get(json, :code_scanning_default_setup),
      code_scanning_default_setup_options: Map.get(json, :code_scanning_default_setup_options),
      code_scanning_delegated_alert_dismissal:
        Map.get(json, :code_scanning_delegated_alert_dismissal),
      code_scanning_options: Map.get(json, :code_scanning_options),
      created_at: Map.get(json, :created_at),
      dependabot_alerts: Map.get(json, :dependabot_alerts),
      dependabot_delegated_alert_dismissal: Map.get(json, :dependabot_delegated_alert_dismissal),
      dependabot_security_updates: Map.get(json, :dependabot_security_updates),
      dependency_graph: Map.get(json, :dependency_graph),
      dependency_graph_autosubmit_action: Map.get(json, :dependency_graph_autosubmit_action),
      dependency_graph_autosubmit_action_options:
        Map.get(json, :dependency_graph_autosubmit_action_options),
      description: Map.get(json, :description),
      enforcement: Map.get(json, :enforcement),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      private_vulnerability_reporting: Map.get(json, :private_vulnerability_reporting),
      secret_scanning: Map.get(json, :secret_scanning),
      secret_scanning_delegated_alert_dismissal:
        Map.get(json, :secret_scanning_delegated_alert_dismissal),
      secret_scanning_delegated_bypass: Map.get(json, :secret_scanning_delegated_bypass),
      secret_scanning_delegated_bypass_options:
        Map.get(json, :secret_scanning_delegated_bypass_options),
      secret_scanning_extended_metadata: Map.get(json, :secret_scanning_extended_metadata),
      secret_scanning_generic_secrets: Map.get(json, :secret_scanning_generic_secrets),
      secret_scanning_non_provider_patterns:
        Map.get(json, :secret_scanning_non_provider_patterns),
      secret_scanning_push_protection: Map.get(json, :secret_scanning_push_protection),
      secret_scanning_validity_checks: Map.get(json, :secret_scanning_validity_checks),
      target_type: Map.get(json, :target_type),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
