# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeScanningVariantAnalysis do
  @moduledoc false
  defstruct [
    :actions_workflow_run_id,
    :actor,
    :completed_at,
    :controller_repo,
    :created_at,
    :failure_reason,
    :id,
    :query_language,
    :query_pack_url,
    :scanned_repositories,
    :skipped_repositories,
    :status,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      actions_workflow_run_id: Map.get(json, :actions_workflow_run_id),
      actor: Noizu.Github.SimpleUser.from_json(Map.get(json, :actor)),
      completed_at: Map.get(json, :completed_at),
      controller_repo: Noizu.Github.SimpleRepository.from_json(Map.get(json, :controller_repo)),
      created_at: Map.get(json, :created_at),
      failure_reason: Map.get(json, :failure_reason),
      id: Map.get(json, :id),
      query_language: Map.get(json, :query_language),
      query_pack_url: Map.get(json, :query_pack_url),
      scanned_repositories: Map.get(json, :scanned_repositories),
      skipped_repositories: Map.get(json, :skipped_repositories),
      status: Map.get(json, :status),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
