# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeScanningSarifsStatus do
  @moduledoc false
  defstruct [
    :analyses_url,
    :errors,
    :processing_status
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      analyses_url: Map.get(json, :analyses_url),
      errors: Map.get(json, :errors),
      processing_status: Map.get(json, :processing_status)
    }
  end

  def from_json(other, _headers), do: other
end
