# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeScanningAutofixCommits do
  @moduledoc false
  defstruct [
    :message,
    :target_ref
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      message: Map.get(json, :message),
      target_ref: Map.get(json, :target_ref)
    }
  end

  def from_json(other, _headers), do: other
end
