# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeScanningAnalysisTool do
  @moduledoc false
  defstruct [
    :guid,
    :name,
    :version
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      guid: Map.get(json, :guid),
      name: Map.get(json, :name),
      version: Map.get(json, :version)
    }
  end

  def from_json(other, _headers), do: other
end
