# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CodeScanningVariantAnalysisRepoTask do
  @moduledoc false
  defstruct [
    :analysis_status,
    :artifact_size_in_bytes,
    :artifact_url,
    :database_commit_sha,
    :failure_message,
    :repository,
    :result_count,
    :source_location_prefix
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      analysis_status: Map.get(json, :analysis_status),
      artifact_size_in_bytes: Map.get(json, :artifact_size_in_bytes),
      artifact_url: Map.get(json, :artifact_url),
      database_commit_sha: Map.get(json, :database_commit_sha),
      failure_message: Map.get(json, :failure_message),
      repository: Noizu.Github.SimpleRepository.from_json(Map.get(json, :repository)),
      result_count: Map.get(json, :result_count),
      source_location_prefix: Map.get(json, :source_location_prefix)
    }
  end

  def from_json(other, _headers), do: other
end
