# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CombinedCommitStatus do
  @moduledoc false
  defstruct [
    :commit_url,
    :repository,
    :sha,
    :state,
    :statuses,
    :total_count,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      commit_url: Map.get(json, :commit_url),
      repository: Noizu.Github.MinimalRepository.from_json(Map.get(json, :repository)),
      sha: Map.get(json, :sha),
      state: Map.get(json, :state),
      statuses:
        Enum.map(Map.get(json, :statuses) || [], &Noizu.Github.SimpleCommitStatus.from_json(&1)),
      total_count: Map.get(json, :total_count),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
