# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CommunityProfile do
  @moduledoc false
  defstruct [
    :content_reports_enabled,
    :description,
    :documentation,
    :files,
    :health_percentage,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      content_reports_enabled: Map.get(json, :content_reports_enabled),
      description: Map.get(json, :description),
      documentation: Map.get(json, :documentation),
      files: Map.get(json, :files),
      health_percentage: Map.get(json, :health_percentage),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
