# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ContributorActivity do
  @moduledoc false
  defstruct [
    :author,
    :total,
    :weeks
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      author: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :author)),
      total: Map.get(json, :total),
      weeks: Map.get(json, :weeks)
    }
  end

  def from_json(other, _headers), do: other
end
