# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CopilotUsageMetrics1DayReport do
  @moduledoc false
  defstruct [
    :download_links,
    :report_day
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      download_links: Map.get(json, :download_links),
      report_day: Map.get(json, :report_day)
    }
  end

  def from_json(other, _headers), do: other
end
