# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CopilotOrganizationSeatBreakdown do
  @moduledoc false
  defstruct [
    :active_this_cycle,
    :added_this_cycle,
    :inactive_this_cycle,
    :pending_cancellation,
    :pending_invitation,
    :total
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      active_this_cycle: Map.get(json, :active_this_cycle),
      added_this_cycle: Map.get(json, :added_this_cycle),
      inactive_this_cycle: Map.get(json, :inactive_this_cycle),
      pending_cancellation: Map.get(json, :pending_cancellation),
      pending_invitation: Map.get(json, :pending_invitation),
      total: Map.get(json, :total)
    }
  end

  def from_json(other, _headers), do: other
end
