# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CopilotSpaceResource do
  @moduledoc false
  defstruct [
    :copilot_chat_attachment_id,
    :created_at,
    :id,
    :metadata,
    :resource_type,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      copilot_chat_attachment_id: Map.get(json, :copilot_chat_attachment_id),
      created_at: Map.get(json, :created_at),
      id: Map.get(json, :id),
      metadata: Map.get(json, :metadata),
      resource_type: Map.get(json, :resource_type),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
