# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.CustomPropertySetPayload do
  @moduledoc false
  defstruct [
    :allowed_values,
    :default_value,
    :description,
    :require_explicit_values,
    :required,
    :value_type,
    :values_editable_by
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      allowed_values: Map.get(json, :allowed_values),
      default_value: Map.get(json, :default_value),
      description: Map.get(json, :description),
      require_explicit_values: Map.get(json, :require_explicit_values),
      required: Map.get(json, :required),
      value_type: Map.get(json, :value_type),
      values_editable_by: Map.get(json, :values_editable_by)
    }
  end

  def from_json(other, _headers), do: other
end
