# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.DeploymentBranchPolicySettings do
  @moduledoc false
  defstruct [
    :custom_branch_policies,
    :protected_branches
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      custom_branch_policies: Map.get(json, :custom_branch_policies),
      protected_branches: Map.get(json, :protected_branches)
    }
  end

  def from_json(other, _headers), do: other
end
