# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.DeployKey do
  @moduledoc false
  defstruct [
    :added_by,
    :created_at,
    :enabled,
    :id,
    :key,
    :last_used,
    :read_only,
    :title,
    :url,
    :verified
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      added_by: Map.get(json, :added_by),
      created_at: Map.get(json, :created_at),
      enabled: Map.get(json, :enabled),
      id: Map.get(json, :id),
      key: Map.get(json, :key),
      last_used: Map.get(json, :last_used),
      read_only: Map.get(json, :read_only),
      title: Map.get(json, :title),
      url: Map.get(json, :url),
      verified: Map.get(json, :verified)
    }
  end

  def from_json(other, _headers), do: other
end
