# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.EnterpriseTeam do
  @moduledoc false
  defstruct [
    :created_at,
    :description,
    :group_id,
    :group_name,
    :html_url,
    :id,
    :members_url,
    :name,
    :notification_setting,
    :organization_selection_type,
    :slug,
    :sync_to_organizations,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      description: Map.get(json, :description),
      group_id: Map.get(json, :group_id),
      group_name: Map.get(json, :group_name),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      members_url: Map.get(json, :members_url),
      name: Map.get(json, :name),
      notification_setting: Map.get(json, :notification_setting),
      organization_selection_type: Map.get(json, :organization_selection_type),
      slug: Map.get(json, :slug),
      sync_to_organizations: Map.get(json, :sync_to_organizations),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
