# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.GitTree do
  @moduledoc false
  defstruct [
    :sha,
    :tree,
    :truncated,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      sha: Map.get(json, :sha),
      tree: Map.get(json, :tree),
      truncated: Map.get(json, :truncated),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
