# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.GpgKey do
  @moduledoc false
  defstruct [
    :can_certify,
    :can_encrypt_comms,
    :can_encrypt_storage,
    :can_sign,
    :created_at,
    :emails,
    :expires_at,
    :id,
    :key_id,
    :name,
    :primary_key_id,
    :public_key,
    :raw_key,
    :revoked,
    :subkeys
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      can_certify: Map.get(json, :can_certify),
      can_encrypt_comms: Map.get(json, :can_encrypt_comms),
      can_encrypt_storage: Map.get(json, :can_encrypt_storage),
      can_sign: Map.get(json, :can_sign),
      created_at: Map.get(json, :created_at),
      emails: Map.get(json, :emails),
      expires_at: Map.get(json, :expires_at),
      id: Map.get(json, :id),
      key_id: Map.get(json, :key_id),
      name: Map.get(json, :name),
      primary_key_id: Map.get(json, :primary_key_id),
      public_key: Map.get(json, :public_key),
      raw_key: Map.get(json, :raw_key),
      revoked: Map.get(json, :revoked),
      subkeys: Map.get(json, :subkeys)
    }
  end

  def from_json(other, _headers), do: other
end
