# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.IntegrationInstallationRequest do
  @moduledoc false
  defstruct [
    :account,
    :created_at,
    :id,
    :node_id,
    :requester
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      account: Map.get(json, :account),
      created_at: Map.get(json, :created_at),
      id: Map.get(json, :id),
      node_id: Map.get(json, :node_id),
      requester: Noizu.Github.SimpleUser.from_json(Map.get(json, :requester))
    }
  end

  def from_json(other, _headers), do: other
end
