# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.IssueEventProjectCard do
  @moduledoc false
  defstruct [
    :column_name,
    :id,
    :previous_column_name,
    :project_id,
    :project_url,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      column_name: Map.get(json, :column_name),
      id: Map.get(json, :id),
      previous_column_name: Map.get(json, :previous_column_name),
      project_id: Map.get(json, :project_id),
      project_url: Map.get(json, :project_url),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
