# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.IssueEventDismissedReview do
  @moduledoc false
  defstruct [
    :dismissal_commit_id,
    :dismissal_message,
    :review_id,
    :state
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      dismissal_commit_id: Map.get(json, :dismissal_commit_id),
      dismissal_message: Map.get(json, :dismissal_message),
      review_id: Map.get(json, :review_id),
      state: Map.get(json, :state)
    }
  end

  def from_json(other, _headers), do: other
end
