# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.IssueType do
  @moduledoc false
  defstruct [
    :color,
    :created_at,
    :description,
    :id,
    :is_enabled,
    :name,
    :node_id,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      color: Map.get(json, :color),
      created_at: Map.get(json, :created_at),
      description: Map.get(json, :description),
      id: Map.get(json, :id),
      is_enabled: Map.get(json, :is_enabled),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
