# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.IssueEvent do
  @moduledoc false
  defstruct [
    :actor,
    :assignee,
    :assigner,
    :author_association,
    :commit_id,
    :commit_url,
    :created_at,
    :dismissed_review,
    :event,
    :id,
    :issue,
    :label,
    :lock_reason,
    :milestone,
    :node_id,
    :performed_via_github_app,
    :project_card,
    :rename,
    :requested_reviewer,
    :requested_team,
    :review_requester,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      actor: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :actor)),
      assignee: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :assignee)),
      assigner: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :assigner)),
      author_association: Map.get(json, :author_association),
      commit_id: Map.get(json, :commit_id),
      commit_url: Map.get(json, :commit_url),
      created_at: Map.get(json, :created_at),
      dismissed_review:
        Noizu.Github.IssueEventDismissedReview.from_json(Map.get(json, :dismissed_review)),
      event: Map.get(json, :event),
      id: Map.get(json, :id),
      issue: Noizu.Github.NullableIssue.from_json(Map.get(json, :issue)),
      label: Noizu.Github.IssueEventLabel.from_json(Map.get(json, :label)),
      lock_reason: Map.get(json, :lock_reason),
      milestone: Noizu.Github.IssueEventMilestone.from_json(Map.get(json, :milestone)),
      node_id: Map.get(json, :node_id),
      performed_via_github_app:
        Noizu.Github.NullableIntegration.from_json(Map.get(json, :performed_via_github_app)),
      project_card: Noizu.Github.IssueEventProjectCard.from_json(Map.get(json, :project_card)),
      rename: Noizu.Github.IssueEventRename.from_json(Map.get(json, :rename)),
      requested_reviewer:
        Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :requested_reviewer)),
      requested_team: Noizu.Github.Team.from_json(Map.get(json, :requested_team)),
      review_requester:
        Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :review_requester)),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
