# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.IssueField do
  @moduledoc false
  defstruct [
    :created_at,
    :data_type,
    :description,
    :id,
    :name,
    :node_id,
    :options,
    :updated_at,
    :visibility
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      data_type: Map.get(json, :data_type),
      description: Map.get(json, :description),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      options: Map.get(json, :options),
      updated_at: Map.get(json, :updated_at),
      visibility: Map.get(json, :visibility)
    }
  end

  def from_json(other, _headers), do: other
end
