# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.IssueDependenciesSummary do
  @moduledoc false
  defstruct [
    :blocked_by,
    :blocking,
    :total_blocked_by,
    :total_blocking
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      blocked_by: Map.get(json, :blocked_by),
      blocking: Map.get(json, :blocking),
      total_blocked_by: Map.get(json, :total_blocked_by),
      total_blocking: Map.get(json, :total_blocking)
    }
  end

  def from_json(other, _headers), do: other
end
