# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Label do
  @moduledoc false
  defstruct [
    :color,
    :default,
    :description,
    :id,
    :name,
    :node_id,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      color: Map.get(json, :color),
      default: Map.get(json, :default),
      description: Map.get(json, :description),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
