# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Manifest do
  @moduledoc false
  defstruct [
    :file,
    :metadata,
    :name,
    :resolved
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      file: Map.get(json, :file),
      metadata: Map.get(json, :metadata),
      name: Map.get(json, :name),
      resolved: Map.get(json, :resolved)
    }
  end

  def from_json(other, _headers), do: other
end
