# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.MarketplacePurchase do
  @moduledoc false
  defstruct [
    :email,
    :id,
    :login,
    :marketplace_pending_change,
    :marketplace_purchase,
    :organization_billing_email,
    :type,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      email: Map.get(json, :email),
      id: Map.get(json, :id),
      login: Map.get(json, :login),
      marketplace_pending_change: Map.get(json, :marketplace_pending_change),
      marketplace_purchase: Map.get(json, :marketplace_purchase),
      organization_billing_email: Map.get(json, :organization_billing_email),
      type: Map.get(json, :type),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
