# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.NetworkSettings do
  @moduledoc false
  defstruct [
    :id,
    :name,
    :network_configuration_id,
    :region,
    :subnet_id
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      network_configuration_id: Map.get(json, :network_configuration_id),
      region: Map.get(json, :region),
      subnet_id: Map.get(json, :subnet_id)
    }
  end

  def from_json(other, _headers), do: other
end
