# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.NetworkConfiguration do
  @moduledoc false
  defstruct [
    :compute_service,
    :created_on,
    :failover_network_enabled,
    :failover_network_settings_ids,
    :id,
    :name,
    :network_settings_ids
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      compute_service: Map.get(json, :compute_service),
      created_on: Map.get(json, :created_on),
      failover_network_enabled: Map.get(json, :failover_network_enabled),
      failover_network_settings_ids: Map.get(json, :failover_network_settings_ids),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      network_settings_ids: Map.get(json, :network_settings_ids)
    }
  end

  def from_json(other, _headers), do: other
end
