# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.NullableSimpleRepository do
  @moduledoc false
  defstruct [
    :archive_url,
    :assignees_url,
    :blobs_url,
    :branches_url,
    :collaborators_url,
    :comments_url,
    :commits_url,
    :compare_url,
    :contents_url,
    :contributors_url,
    :deployments_url,
    :description,
    :downloads_url,
    :events_url,
    :fork,
    :forks_url,
    :full_name,
    :git_commits_url,
    :git_refs_url,
    :git_tags_url,
    :hooks_url,
    :html_url,
    :id,
    :issue_comment_url,
    :issue_events_url,
    :issues_url,
    :keys_url,
    :labels_url,
    :languages_url,
    :merges_url,
    :milestones_url,
    :name,
    :node_id,
    :notifications_url,
    :owner,
    :private,
    :pulls_url,
    :releases_url,
    :stargazers_url,
    :statuses_url,
    :subscribers_url,
    :subscription_url,
    :tags_url,
    :teams_url,
    :trees_url,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      archive_url: Map.get(json, :archive_url),
      assignees_url: Map.get(json, :assignees_url),
      blobs_url: Map.get(json, :blobs_url),
      branches_url: Map.get(json, :branches_url),
      collaborators_url: Map.get(json, :collaborators_url),
      comments_url: Map.get(json, :comments_url),
      commits_url: Map.get(json, :commits_url),
      compare_url: Map.get(json, :compare_url),
      contents_url: Map.get(json, :contents_url),
      contributors_url: Map.get(json, :contributors_url),
      deployments_url: Map.get(json, :deployments_url),
      description: Map.get(json, :description),
      downloads_url: Map.get(json, :downloads_url),
      events_url: Map.get(json, :events_url),
      fork: Map.get(json, :fork),
      forks_url: Map.get(json, :forks_url),
      full_name: Map.get(json, :full_name),
      git_commits_url: Map.get(json, :git_commits_url),
      git_refs_url: Map.get(json, :git_refs_url),
      git_tags_url: Map.get(json, :git_tags_url),
      hooks_url: Map.get(json, :hooks_url),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      issue_comment_url: Map.get(json, :issue_comment_url),
      issue_events_url: Map.get(json, :issue_events_url),
      issues_url: Map.get(json, :issues_url),
      keys_url: Map.get(json, :keys_url),
      labels_url: Map.get(json, :labels_url),
      languages_url: Map.get(json, :languages_url),
      merges_url: Map.get(json, :merges_url),
      milestones_url: Map.get(json, :milestones_url),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      notifications_url: Map.get(json, :notifications_url),
      owner: Noizu.Github.SimpleUser.from_json(Map.get(json, :owner)),
      private: Map.get(json, :private),
      pulls_url: Map.get(json, :pulls_url),
      releases_url: Map.get(json, :releases_url),
      stargazers_url: Map.get(json, :stargazers_url),
      statuses_url: Map.get(json, :statuses_url),
      subscribers_url: Map.get(json, :subscribers_url),
      subscription_url: Map.get(json, :subscription_url),
      tags_url: Map.get(json, :tags_url),
      teams_url: Map.get(json, :teams_url),
      trees_url: Map.get(json, :trees_url),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
