# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.NullableCodespaceMachine do
  @moduledoc false
  defstruct [
    :cpus,
    :display_name,
    :memory_in_bytes,
    :name,
    :operating_system,
    :prebuild_availability,
    :storage_in_bytes
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      cpus: Map.get(json, :cpus),
      display_name: Map.get(json, :display_name),
      memory_in_bytes: Map.get(json, :memory_in_bytes),
      name: Map.get(json, :name),
      operating_system: Map.get(json, :operating_system),
      prebuild_availability: Map.get(json, :prebuild_availability),
      storage_in_bytes: Map.get(json, :storage_in_bytes)
    }
  end

  def from_json(other, _headers), do: other
end
