# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.NullableSimpleCommit do
  @moduledoc false
  defstruct [
    :author,
    :committer,
    :id,
    :message,
    :timestamp,
    :tree_id
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      author: Map.get(json, :author),
      committer: Map.get(json, :committer),
      id: Map.get(json, :id),
      message: Map.get(json, :message),
      timestamp: Map.get(json, :timestamp),
      tree_id: Map.get(json, :tree_id)
    }
  end

  def from_json(other, _headers), do: other
end
