# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.OidcCustomSubRepo do
  @moduledoc false
  defstruct [
    :include_claim_keys,
    :sub_claim_prefix,
    :use_default,
    :use_immutable_subject
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      include_claim_keys: Map.get(json, :include_claim_keys),
      sub_claim_prefix: Map.get(json, :sub_claim_prefix),
      use_default: Map.get(json, :use_default),
      use_immutable_subject: Map.get(json, :use_immutable_subject)
    }
  end

  def from_json(other, _headers), do: other
end
