# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.OrgHook do
  @moduledoc false
  defstruct [
    :active,
    :config,
    :created_at,
    :deliveries_url,
    :events,
    :id,
    :name,
    :ping_url,
    :type,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      active: Map.get(json, :active),
      config: Map.get(json, :config),
      created_at: Map.get(json, :created_at),
      deliveries_url: Map.get(json, :deliveries_url),
      events: Map.get(json, :events),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      ping_url: Map.get(json, :ping_url),
      type: Map.get(json, :type),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
