# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.OrgRepoCustomPropertyValues do
  @moduledoc false
  defstruct [
    :properties,
    :repository_full_name,
    :repository_id,
    :repository_name
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      properties:
        Enum.map(
          Map.get(json, :properties) || [],
          &Noizu.Github.CustomPropertyValue.from_json(&1)
        ),
      repository_full_name: Map.get(json, :repository_full_name),
      repository_id: Map.get(json, :repository_id),
      repository_name: Map.get(json, :repository_name)
    }
  end

  def from_json(other, _headers), do: other
end
