# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.OrgPrivateRegistryConfigurationWithSelectedRepositories do
  @moduledoc false
  defstruct [
    :account_id,
    :api_host,
    :audience,
    :auth_type,
    :aws_region,
    :client_id,
    :created_at,
    :domain,
    :domain_owner,
    :identity_mapping_name,
    :jfrog_oidc_provider_name,
    :name,
    :namespace,
    :registry_type,
    :replaces_base,
    :role_name,
    :selected_repository_ids,
    :service_account,
    :service_slug,
    :tenant_id,
    :updated_at,
    :url,
    :username,
    :visibility,
    :workload_identity_provider
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      account_id: Map.get(json, :account_id),
      api_host: Map.get(json, :api_host),
      audience: Map.get(json, :audience),
      auth_type: Map.get(json, :auth_type),
      aws_region: Map.get(json, :aws_region),
      client_id: Map.get(json, :client_id),
      created_at: Map.get(json, :created_at),
      domain: Map.get(json, :domain),
      domain_owner: Map.get(json, :domain_owner),
      identity_mapping_name: Map.get(json, :identity_mapping_name),
      jfrog_oidc_provider_name: Map.get(json, :jfrog_oidc_provider_name),
      name: Map.get(json, :name),
      namespace: Map.get(json, :namespace),
      registry_type: Map.get(json, :registry_type),
      replaces_base: Map.get(json, :replaces_base),
      role_name: Map.get(json, :role_name),
      selected_repository_ids: Map.get(json, :selected_repository_ids),
      service_account: Map.get(json, :service_account),
      service_slug: Map.get(json, :service_slug),
      tenant_id: Map.get(json, :tenant_id),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url),
      username: Map.get(json, :username),
      visibility: Map.get(json, :visibility),
      workload_identity_provider: Map.get(json, :workload_identity_provider)
    }
  end

  def from_json(other, _headers), do: other
end
