# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.OrganizationRole do
  @moduledoc false
  defstruct [
    :base_role,
    :created_at,
    :description,
    :id,
    :name,
    :organization,
    :permissions,
    :source,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      base_role: Map.get(json, :base_role),
      created_at: Map.get(json, :created_at),
      description: Map.get(json, :description),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      organization: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :organization)),
      permissions: Map.get(json, :permissions),
      source: Map.get(json, :source),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
