# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.OrganizationSimpleWebhooks do
  @moduledoc false
  defstruct [
    :avatar_url,
    :description,
    :events_url,
    :hooks_url,
    :id,
    :issues_url,
    :login,
    :members_url,
    :node_id,
    :public_members_url,
    :repos_url,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      avatar_url: Map.get(json, :avatar_url),
      description: Map.get(json, :description),
      events_url: Map.get(json, :events_url),
      hooks_url: Map.get(json, :hooks_url),
      id: Map.get(json, :id),
      issues_url: Map.get(json, :issues_url),
      login: Map.get(json, :login),
      members_url: Map.get(json, :members_url),
      node_id: Map.get(json, :node_id),
      public_members_url: Map.get(json, :public_members_url),
      repos_url: Map.get(json, :repos_url),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
