# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Package do
  @moduledoc false
  defstruct [
    :created_at,
    :html_url,
    :id,
    :name,
    :owner,
    :package_type,
    :repository,
    :updated_at,
    :url,
    :version_count,
    :visibility
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      owner: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :owner)),
      package_type: Map.get(json, :package_type),
      repository: Noizu.Github.NullableMinimalRepository.from_json(Map.get(json, :repository)),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url),
      version_count: Map.get(json, :version_count),
      visibility: Map.get(json, :visibility)
    }
  end

  def from_json(other, _headers), do: other
end
