# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.PackageVersion do
  @moduledoc false
  defstruct [
    :created_at,
    :deleted_at,
    :description,
    :html_url,
    :id,
    :license,
    :metadata,
    :name,
    :package_html_url,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      deleted_at: Map.get(json, :deleted_at),
      description: Map.get(json, :description),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      license: Map.get(json, :license),
      metadata: Map.get(json, :metadata),
      name: Map.get(json, :name),
      package_html_url: Map.get(json, :package_html_url),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
