# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.PagesHttpsCertificate do
  @moduledoc false
  defstruct [
    :description,
    :domains,
    :expires_at,
    :state
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      description: Map.get(json, :description),
      domains: Map.get(json, :domains),
      expires_at: Map.get(json, :expires_at),
      state: Map.get(json, :state)
    }
  end

  def from_json(other, _headers), do: other
end
