# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.PageBuild do
  @moduledoc false
  defstruct [
    :commit,
    :created_at,
    :duration,
    :error,
    :pusher,
    :status,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      commit: Map.get(json, :commit),
      created_at: Map.get(json, :created_at),
      duration: Map.get(json, :duration),
      error: Map.get(json, :error),
      pusher: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :pusher)),
      status: Map.get(json, :status),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
