# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ProjectsV2 do
  @moduledoc false
  defstruct [
    :closed_at,
    :created_at,
    :creator,
    :deleted_at,
    :deleted_by,
    :description,
    :id,
    :is_template,
    :latest_status_update,
    :node_id,
    :number,
    :owner,
    :public,
    :short_description,
    :state,
    :title,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      closed_at: Map.get(json, :closed_at),
      created_at: Map.get(json, :created_at),
      creator: Noizu.Github.SimpleUser.from_json(Map.get(json, :creator)),
      deleted_at: Map.get(json, :deleted_at),
      deleted_by: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :deleted_by)),
      description: Map.get(json, :description),
      id: Map.get(json, :id),
      is_template: Map.get(json, :is_template),
      latest_status_update:
        Noizu.Github.NullableProjectsV2StatusUpdate.from_json(
          Map.get(json, :latest_status_update)
        ),
      node_id: Map.get(json, :node_id),
      number: Map.get(json, :number),
      owner: Noizu.Github.SimpleUser.from_json(Map.get(json, :owner)),
      public: Map.get(json, :public),
      short_description: Map.get(json, :short_description),
      state: Map.get(json, :state),
      title: Map.get(json, :title),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
