# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ProtectedBranchPullRequestReview do
  @moduledoc false
  defstruct [
    :bypass_pull_request_allowances,
    :dismiss_stale_reviews,
    :dismissal_restrictions,
    :require_code_owner_reviews,
    :require_last_push_approval,
    :required_approving_review_count,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      bypass_pull_request_allowances: Map.get(json, :bypass_pull_request_allowances),
      dismiss_stale_reviews: Map.get(json, :dismiss_stale_reviews),
      dismissal_restrictions: Map.get(json, :dismissal_restrictions),
      require_code_owner_reviews: Map.get(json, :require_code_owner_reviews),
      require_last_push_approval: Map.get(json, :require_last_push_approval),
      required_approving_review_count: Map.get(json, :required_approving_review_count),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
