# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.PullRequestEvent do
  @moduledoc false
  defstruct [
    :action,
    :assignee,
    :assignees,
    :label,
    :labels,
    :number,
    :pull_request
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      action: Map.get(json, :action),
      assignee: Noizu.Github.SimpleUser.from_json(Map.get(json, :assignee)),
      assignees:
        Enum.map(Map.get(json, :assignees) || [], &Noizu.Github.SimpleUser.from_json(&1)),
      label: Noizu.Github.Label.from_json(Map.get(json, :label)),
      labels: Enum.map(Map.get(json, :labels) || [], &Noizu.Github.Label.from_json(&1)),
      number: Map.get(json, :number),
      pull_request: Noizu.Github.PullRequestMinimal.from_json(Map.get(json, :pull_request))
    }
  end

  def from_json(other, _headers), do: other
end
