# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.PushEvent do
  @moduledoc false
  defstruct [
    :before,
    :head,
    :push_id,
    :ref,
    :repository_id
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      before: Map.get(json, :before),
      head: Map.get(json, :head),
      push_id: Map.get(json, :push_id),
      ref: Map.get(json, :ref),
      repository_id: Map.get(json, :repository_id)
    }
  end

  def from_json(other, _headers), do: other
end
