# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Raw do
  @moduledoc """
  Generic passthrough result for endpoints without a dedicated schema
  (inline objects, unions, empty `204` bodies). Carries the decoded body in
  `:data` and any pagination links in `:links`.
  """
  defstruct [:data, :links]

  def from_json(json, headers \\ [])

  def from_json(json, headers) do
    %__MODULE__{data: json, links: Noizu.Github.extract_links(headers)}
  end
end
