# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.ReactionRollup do
  @moduledoc false
  defstruct [
    :"+1",
    :"-1",
    :confused,
    :eyes,
    :heart,
    :hooray,
    :laugh,
    :rocket,
    :total_count,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      "+1": Map.get(json, :"+1"),
      "-1": Map.get(json, :"-1"),
      confused: Map.get(json, :confused),
      eyes: Map.get(json, :eyes),
      heart: Map.get(json, :heart),
      hooray: Map.get(json, :hooray),
      laugh: Map.get(json, :laugh),
      rocket: Map.get(json, :rocket),
      total_count: Map.get(json, :total_count),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
