# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Reaction do
  @moduledoc false
  defstruct [
    :content,
    :created_at,
    :id,
    :node_id,
    :user
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      content: Map.get(json, :content),
      created_at: Map.get(json, :created_at),
      id: Map.get(json, :id),
      node_id: Map.get(json, :node_id),
      user: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :user))
    }
  end

  def from_json(other, _headers), do: other
end
