# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RepositoryRuleParamsWorkflowFileReference do
  @moduledoc false
  defstruct [
    :path,
    :ref,
    :repository_id,
    :sha
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      path: Map.get(json, :path),
      ref: Map.get(json, :ref),
      repository_id: Map.get(json, :repository_id),
      sha: Map.get(json, :sha)
    }
  end

  def from_json(other, _headers), do: other
end
