# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RepositoryInvitation do
  @moduledoc false
  defstruct [
    :created_at,
    :expired,
    :html_url,
    :id,
    :invitee,
    :inviter,
    :node_id,
    :permissions,
    :repository,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      expired: Map.get(json, :expired),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      invitee: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :invitee)),
      inviter: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :inviter)),
      node_id: Map.get(json, :node_id),
      permissions: Map.get(json, :permissions),
      repository: Noizu.Github.MinimalRepository.from_json(Map.get(json, :repository)),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
