# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RepositoryRuleParamsRequiredReviewerConfiguration do
  @moduledoc false
  defstruct [
    :file_patterns,
    :minimum_approvals,
    :reviewer
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      file_patterns: Map.get(json, :file_patterns),
      minimum_approvals: Map.get(json, :minimum_approvals),
      reviewer: Noizu.Github.RepositoryRuleParamsReviewer.from_json(Map.get(json, :reviewer))
    }
  end

  def from_json(other, _headers), do: other
end
