# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RepositoryCollaboratorPermission do
  @moduledoc false
  defstruct [
    :permission,
    :role_name,
    :user
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      permission: Map.get(json, :permission),
      role_name: Map.get(json, :role_name),
      user: Noizu.Github.NullableCollaborator.from_json(Map.get(json, :user))
    }
  end

  def from_json(other, _headers), do: other
end
