# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RepositoryRuleParamsDismissalRestriction do
  @moduledoc false
  defstruct [
    :allowed_actors,
    :enabled
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      allowed_actors:
        Enum.map(
          Map.get(json, :allowed_actors) || [],
          &Noizu.Github.RepositoryRuleParamsActor.from_json(&1)
        ),
      enabled: Map.get(json, :enabled)
    }
  end

  def from_json(other, _headers), do: other
end
