# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RepositoryRuleViolationError do
  @moduledoc false
  defstruct [
    :documentation_url,
    :message,
    :metadata,
    :status
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      documentation_url: Map.get(json, :documentation_url),
      message: Map.get(json, :message),
      metadata: Map.get(json, :metadata),
      status: Map.get(json, :status)
    }
  end

  def from_json(other, _headers), do: other
end
