# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RepositoryAdvisoryCreate do
  @moduledoc false
  defstruct [
    :credits,
    :cve_id,
    :cvss_vector_string,
    :cwe_ids,
    :description,
    :severity,
    :start_private_fork,
    :summary,
    :vulnerabilities
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      credits: Map.get(json, :credits),
      cve_id: Map.get(json, :cve_id),
      cvss_vector_string: Map.get(json, :cvss_vector_string),
      cwe_ids: Map.get(json, :cwe_ids),
      description: Map.get(json, :description),
      severity: Map.get(json, :severity),
      start_private_fork: Map.get(json, :start_private_fork),
      summary: Map.get(json, :summary),
      vulnerabilities: Map.get(json, :vulnerabilities)
    }
  end

  def from_json(other, _headers), do: other
end
