# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RepositorySubscription do
  @moduledoc false
  defstruct [
    :created_at,
    :ignored,
    :reason,
    :repository_url,
    :subscribed,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      ignored: Map.get(json, :ignored),
      reason: Map.get(json, :reason),
      repository_url: Map.get(json, :repository_url),
      subscribed: Map.get(json, :subscribed),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
