# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Root do
  @moduledoc false
  defstruct [
    :authorizations_url,
    :code_search_url,
    :commit_search_url,
    :current_user_authorizations_html_url,
    :current_user_repositories_url,
    :current_user_url,
    :emails_url,
    :emojis_url,
    :events_url,
    :feeds_url,
    :followers_url,
    :following_url,
    :gists_url,
    :hub_url,
    :issue_search_url,
    :issues_url,
    :keys_url,
    :label_search_url,
    :notifications_url,
    :organization_repositories_url,
    :organization_teams_url,
    :organization_url,
    :public_gists_url,
    :rate_limit_url,
    :repository_search_url,
    :repository_url,
    :starred_gists_url,
    :starred_url,
    :topic_search_url,
    :user_organizations_url,
    :user_repositories_url,
    :user_search_url,
    :user_url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      authorizations_url: Map.get(json, :authorizations_url),
      code_search_url: Map.get(json, :code_search_url),
      commit_search_url: Map.get(json, :commit_search_url),
      current_user_authorizations_html_url: Map.get(json, :current_user_authorizations_html_url),
      current_user_repositories_url: Map.get(json, :current_user_repositories_url),
      current_user_url: Map.get(json, :current_user_url),
      emails_url: Map.get(json, :emails_url),
      emojis_url: Map.get(json, :emojis_url),
      events_url: Map.get(json, :events_url),
      feeds_url: Map.get(json, :feeds_url),
      followers_url: Map.get(json, :followers_url),
      following_url: Map.get(json, :following_url),
      gists_url: Map.get(json, :gists_url),
      hub_url: Map.get(json, :hub_url),
      issue_search_url: Map.get(json, :issue_search_url),
      issues_url: Map.get(json, :issues_url),
      keys_url: Map.get(json, :keys_url),
      label_search_url: Map.get(json, :label_search_url),
      notifications_url: Map.get(json, :notifications_url),
      organization_repositories_url: Map.get(json, :organization_repositories_url),
      organization_teams_url: Map.get(json, :organization_teams_url),
      organization_url: Map.get(json, :organization_url),
      public_gists_url: Map.get(json, :public_gists_url),
      rate_limit_url: Map.get(json, :rate_limit_url),
      repository_search_url: Map.get(json, :repository_search_url),
      repository_url: Map.get(json, :repository_url),
      starred_gists_url: Map.get(json, :starred_gists_url),
      starred_url: Map.get(json, :starred_url),
      topic_search_url: Map.get(json, :topic_search_url),
      user_organizations_url: Map.get(json, :user_organizations_url),
      user_repositories_url: Map.get(json, :user_repositories_url),
      user_search_url: Map.get(json, :user_search_url),
      user_url: Map.get(json, :user_url)
    }
  end

  def from_json(other, _headers), do: other
end
