# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RulesetVersion do
  @moduledoc false
  defstruct [
    :actor,
    :updated_at,
    :version_id
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      actor: Map.get(json, :actor),
      updated_at: Map.get(json, :updated_at),
      version_id: Map.get(json, :version_id)
    }
  end

  def from_json(other, _headers), do: other
end
