# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.RunnerApplication do
  @moduledoc false
  defstruct [
    :architecture,
    :download_url,
    :filename,
    :os,
    :sha256_checksum,
    :temp_download_token
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      architecture: Map.get(json, :architecture),
      download_url: Map.get(json, :download_url),
      filename: Map.get(json, :filename),
      os: Map.get(json, :os),
      sha256_checksum: Map.get(json, :sha256_checksum),
      temp_download_token: Map.get(json, :temp_download_token)
    }
  end

  def from_json(other, _headers), do: other
end
