# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.SecretScanningLocationWikiCommit do
  @moduledoc false
  defstruct [
    :blob_sha,
    :commit_sha,
    :commit_url,
    :end_column,
    :end_line,
    :page_url,
    :path,
    :start_column,
    :start_line
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      blob_sha: Map.get(json, :blob_sha),
      commit_sha: Map.get(json, :commit_sha),
      commit_url: Map.get(json, :commit_url),
      end_column: Map.get(json, :end_column),
      end_line: Map.get(json, :end_line),
      page_url: Map.get(json, :page_url),
      path: Map.get(json, :path),
      start_column: Map.get(json, :start_column),
      start_line: Map.get(json, :start_line)
    }
  end

  def from_json(other, _headers), do: other
end
