# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.SecretScanningPatternOverride do
  @moduledoc false
  defstruct [
    :alert_total,
    :alert_total_percentage,
    :bypass_rate,
    :custom_pattern_version,
    :default_setting,
    :display_name,
    :enterprise_setting,
    :false_positive_rate,
    :false_positives,
    :setting,
    :slug,
    :token_type
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      alert_total: Map.get(json, :alert_total),
      alert_total_percentage: Map.get(json, :alert_total_percentage),
      bypass_rate: Map.get(json, :bypass_rate),
      custom_pattern_version: Map.get(json, :custom_pattern_version),
      default_setting: Map.get(json, :default_setting),
      display_name: Map.get(json, :display_name),
      enterprise_setting: Map.get(json, :enterprise_setting),
      false_positive_rate: Map.get(json, :false_positive_rate),
      false_positives: Map.get(json, :false_positives),
      setting: Map.get(json, :setting),
      slug: Map.get(json, :slug),
      token_type: Map.get(json, :token_type)
    }
  end

  def from_json(other, _headers), do: other
end
