# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.SecretScanningPushProtectionBypass do
  @moduledoc false
  defstruct [
    :expire_at,
    :reason,
    :token_type
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      expire_at: Map.get(json, :expire_at),
      reason: Map.get(json, :reason),
      token_type: Map.get(json, :token_type)
    }
  end

  def from_json(other, _headers), do: other
end
