# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.SecretScanningScanHistory do
  @moduledoc false
  defstruct [
    :backfill_scans,
    :custom_pattern_backfill_scans,
    :generic_secrets_backfill_scans,
    :incremental_scans,
    :pattern_update_scans
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      backfill_scans:
        Enum.map(
          Map.get(json, :backfill_scans) || [],
          &Noizu.Github.SecretScanningScan.from_json(&1)
        ),
      custom_pattern_backfill_scans: Map.get(json, :custom_pattern_backfill_scans),
      generic_secrets_backfill_scans:
        Enum.map(
          Map.get(json, :generic_secrets_backfill_scans) || [],
          &Noizu.Github.SecretScanningScan.from_json(&1)
        ),
      incremental_scans:
        Enum.map(
          Map.get(json, :incremental_scans) || [],
          &Noizu.Github.SecretScanningScan.from_json(&1)
        ),
      pattern_update_scans:
        Enum.map(
          Map.get(json, :pattern_update_scans) || [],
          &Noizu.Github.SecretScanningScan.from_json(&1)
        )
    }
  end

  def from_json(other, _headers), do: other
end
