# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.SecretScanningPatternConfiguration do
  @moduledoc false
  defstruct [
    :custom_pattern_overrides,
    :pattern_config_version,
    :provider_pattern_overrides
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      custom_pattern_overrides:
        Enum.map(
          Map.get(json, :custom_pattern_overrides) || [],
          &Noizu.Github.SecretScanningPatternOverride.from_json(&1)
        ),
      pattern_config_version: Map.get(json, :pattern_config_version),
      provider_pattern_overrides:
        Enum.map(
          Map.get(json, :provider_pattern_overrides) || [],
          &Noizu.Github.SecretScanningPatternOverride.from_json(&1)
        )
    }
  end

  def from_json(other, _headers), do: other
end
