# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.SelfHostedRunnersSettings do
  @moduledoc false
  defstruct [
    :enabled_repositories,
    :selected_repositories_url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      enabled_repositories: Map.get(json, :enabled_repositories),
      selected_repositories_url: Map.get(json, :selected_repositories_url)
    }
  end

  def from_json(other, _headers), do: other
end
