# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.SimpleClassroomUser do
  @moduledoc false
  defstruct [
    :avatar_url,
    :html_url,
    :id,
    :login
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      avatar_url: Map.get(json, :avatar_url),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      login: Map.get(json, :login)
    }
  end

  def from_json(other, _headers), do: other
end
