# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Snapshot do
  @moduledoc false
  defstruct [
    :detector,
    :job,
    :manifests,
    :metadata,
    :ref,
    :scanned,
    :sha,
    :version
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      detector: Map.get(json, :detector),
      job: Map.get(json, :job),
      manifests: Map.get(json, :manifests),
      metadata: Map.get(json, :metadata),
      ref: Map.get(json, :ref),
      scanned: Map.get(json, :scanned),
      sha: Map.get(json, :sha),
      version: Map.get(json, :version)
    }
  end

  def from_json(other, _headers), do: other
end
