# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Status do
  @moduledoc false
  defstruct [
    :avatar_url,
    :context,
    :created_at,
    :creator,
    :description,
    :id,
    :node_id,
    :state,
    :target_url,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      avatar_url: Map.get(json, :avatar_url),
      context: Map.get(json, :context),
      created_at: Map.get(json, :created_at),
      creator: Noizu.Github.NullableSimpleUser.from_json(Map.get(json, :creator)),
      description: Map.get(json, :description),
      id: Map.get(json, :id),
      node_id: Map.get(json, :node_id),
      state: Map.get(json, :state),
      target_url: Map.get(json, :target_url),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
