# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.StatusCheckPolicy do
  @moduledoc false
  defstruct [
    :checks,
    :contexts,
    :contexts_url,
    :strict,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      checks: Map.get(json, :checks),
      contexts: Map.get(json, :contexts),
      contexts_url: Map.get(json, :contexts_url),
      strict: Map.get(json, :strict),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
