# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Tag do
  @moduledoc false
  defstruct [
    :commit,
    :name,
    :node_id,
    :tarball_url,
    :zipball_url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      commit: Map.get(json, :commit),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      tarball_url: Map.get(json, :tarball_url),
      zipball_url: Map.get(json, :zipball_url)
    }
  end

  def from_json(other, _headers), do: other
end
