# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.TeamFull do
  @moduledoc false
  defstruct [
    :created_at,
    :description,
    :enterprise_id,
    :html_url,
    :id,
    :ldap_dn,
    :members_count,
    :members_url,
    :name,
    :node_id,
    :notification_setting,
    :organization,
    :organization_id,
    :parent,
    :permission,
    :privacy,
    :repos_count,
    :repositories_url,
    :slug,
    :type,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      description: Map.get(json, :description),
      enterprise_id: Map.get(json, :enterprise_id),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      ldap_dn: Map.get(json, :ldap_dn),
      members_count: Map.get(json, :members_count),
      members_url: Map.get(json, :members_url),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      notification_setting: Map.get(json, :notification_setting),
      organization: Noizu.Github.TeamOrganization.from_json(Map.get(json, :organization)),
      organization_id: Map.get(json, :organization_id),
      parent: Noizu.Github.NullableTeamSimple.from_json(Map.get(json, :parent)),
      permission: Map.get(json, :permission),
      privacy: Map.get(json, :privacy),
      repos_count: Map.get(json, :repos_count),
      repositories_url: Map.get(json, :repositories_url),
      slug: Map.get(json, :slug),
      type: Map.get(json, :type),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
