# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.TeamOrganization do
  @moduledoc false
  defstruct [
    :archived_at,
    :avatar_url,
    :billing_email,
    :blog,
    :collaborators,
    :company,
    :created_at,
    :default_repository_permission,
    :description,
    :disk_usage,
    :email,
    :events_url,
    :followers,
    :following,
    :has_organization_projects,
    :has_repository_projects,
    :hooks_url,
    :html_url,
    :id,
    :is_verified,
    :issues_url,
    :location,
    :login,
    :members_allowed_repository_creation_type,
    :members_can_create_internal_repositories,
    :members_can_create_pages,
    :members_can_create_private_pages,
    :members_can_create_private_repositories,
    :members_can_create_public_pages,
    :members_can_create_public_repositories,
    :members_can_create_repositories,
    :members_can_fork_private_repositories,
    :members_url,
    :name,
    :node_id,
    :owned_private_repos,
    :plan,
    :private_gists,
    :public_gists,
    :public_members_url,
    :public_repos,
    :repos_url,
    :total_private_repos,
    :twitter_username,
    :two_factor_requirement_enabled,
    :type,
    :updated_at,
    :url,
    :web_commit_signoff_required
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      archived_at: Map.get(json, :archived_at),
      avatar_url: Map.get(json, :avatar_url),
      billing_email: Map.get(json, :billing_email),
      blog: Map.get(json, :blog),
      collaborators: Map.get(json, :collaborators),
      company: Map.get(json, :company),
      created_at: Map.get(json, :created_at),
      default_repository_permission: Map.get(json, :default_repository_permission),
      description: Map.get(json, :description),
      disk_usage: Map.get(json, :disk_usage),
      email: Map.get(json, :email),
      events_url: Map.get(json, :events_url),
      followers: Map.get(json, :followers),
      following: Map.get(json, :following),
      has_organization_projects: Map.get(json, :has_organization_projects),
      has_repository_projects: Map.get(json, :has_repository_projects),
      hooks_url: Map.get(json, :hooks_url),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      is_verified: Map.get(json, :is_verified),
      issues_url: Map.get(json, :issues_url),
      location: Map.get(json, :location),
      login: Map.get(json, :login),
      members_allowed_repository_creation_type:
        Map.get(json, :members_allowed_repository_creation_type),
      members_can_create_internal_repositories:
        Map.get(json, :members_can_create_internal_repositories),
      members_can_create_pages: Map.get(json, :members_can_create_pages),
      members_can_create_private_pages: Map.get(json, :members_can_create_private_pages),
      members_can_create_private_repositories:
        Map.get(json, :members_can_create_private_repositories),
      members_can_create_public_pages: Map.get(json, :members_can_create_public_pages),
      members_can_create_public_repositories:
        Map.get(json, :members_can_create_public_repositories),
      members_can_create_repositories: Map.get(json, :members_can_create_repositories),
      members_can_fork_private_repositories:
        Map.get(json, :members_can_fork_private_repositories),
      members_url: Map.get(json, :members_url),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      owned_private_repos: Map.get(json, :owned_private_repos),
      plan: Map.get(json, :plan),
      private_gists: Map.get(json, :private_gists),
      public_gists: Map.get(json, :public_gists),
      public_members_url: Map.get(json, :public_members_url),
      public_repos: Map.get(json, :public_repos),
      repos_url: Map.get(json, :repos_url),
      total_private_repos: Map.get(json, :total_private_repos),
      twitter_username: Map.get(json, :twitter_username),
      two_factor_requirement_enabled: Map.get(json, :two_factor_requirement_enabled),
      type: Map.get(json, :type),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url),
      web_commit_signoff_required: Map.get(json, :web_commit_signoff_required)
    }
  end

  def from_json(other, _headers), do: other
end
