# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.TimelineCommentEvent do
  @moduledoc false
  defstruct [
    :actor,
    :author_association,
    :body,
    :body_html,
    :body_text,
    :created_at,
    :event,
    :html_url,
    :id,
    :issue_url,
    :node_id,
    :performed_via_github_app,
    :pin,
    :reactions,
    :updated_at,
    :url,
    :user
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      actor: Noizu.Github.SimpleUser.from_json(Map.get(json, :actor)),
      author_association: Map.get(json, :author_association),
      body: Map.get(json, :body),
      body_html: Map.get(json, :body_html),
      body_text: Map.get(json, :body_text),
      created_at: Map.get(json, :created_at),
      event: Map.get(json, :event),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      issue_url: Map.get(json, :issue_url),
      node_id: Map.get(json, :node_id),
      performed_via_github_app:
        Noizu.Github.NullableIntegration.from_json(Map.get(json, :performed_via_github_app)),
      pin: Noizu.Github.NullablePinnedIssueComment.from_json(Map.get(json, :pin)),
      reactions: Noizu.Github.ReactionRollup.from_json(Map.get(json, :reactions)),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url),
      user: Noizu.Github.SimpleUser.from_json(Map.get(json, :user))
    }
  end

  def from_json(other, _headers), do: other
end
