# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.UpdateBudget do
  @moduledoc false
  defstruct [
    :budget,
    :message
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      budget: Map.get(json, :budget),
      message: Map.get(json, :message)
    }
  end

  def from_json(other, _headers), do: other
end
