# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhookMergeGroupDestroyed do
  @moduledoc false
  defstruct [
    :action,
    :installation,
    :merge_group,
    :organization,
    :reason,
    :repository,
    :sender
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      action: Map.get(json, :action),
      installation: Noizu.Github.SimpleInstallation.from_json(Map.get(json, :installation)),
      merge_group: Noizu.Github.MergeGroup.from_json(Map.get(json, :merge_group)),
      organization:
        Noizu.Github.OrganizationSimpleWebhooks.from_json(Map.get(json, :organization)),
      reason: Map.get(json, :reason),
      repository: Noizu.Github.RepositoryWebhooks.from_json(Map.get(json, :repository)),
      sender: Noizu.Github.SimpleUser.from_json(Map.get(json, :sender))
    }
  end

  def from_json(other, _headers), do: other
end
