# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhookDeploymentStatusCreated do
  @moduledoc false
  defstruct [
    :action,
    :check_run,
    :deployment,
    :deployment_status,
    :enterprise,
    :installation,
    :organization,
    :repository,
    :sender,
    :workflow,
    :workflow_run
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      action: Map.get(json, :action),
      check_run: Map.get(json, :check_run),
      deployment: Map.get(json, :deployment),
      deployment_status: Map.get(json, :deployment_status),
      enterprise: Noizu.Github.EnterpriseWebhooks.from_json(Map.get(json, :enterprise)),
      installation: Noizu.Github.SimpleInstallation.from_json(Map.get(json, :installation)),
      organization:
        Noizu.Github.OrganizationSimpleWebhooks.from_json(Map.get(json, :organization)),
      repository: Noizu.Github.RepositoryWebhooks.from_json(Map.get(json, :repository)),
      sender: Noizu.Github.SimpleUser.from_json(Map.get(json, :sender)),
      workflow: Noizu.Github.WebhooksWorkflow.from_json(Map.get(json, :workflow)),
      workflow_run: Map.get(json, :workflow_run)
    }
  end

  def from_json(other, _headers), do: other
end
