# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhooksAnswer do
  @moduledoc false
  defstruct [
    :author_association,
    :body,
    :child_comment_count,
    :created_at,
    :discussion_id,
    :html_url,
    :id,
    :node_id,
    :parent_id,
    :reactions,
    :repository_url,
    :updated_at,
    :user
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      author_association: Map.get(json, :author_association),
      body: Map.get(json, :body),
      child_comment_count: Map.get(json, :child_comment_count),
      created_at: Map.get(json, :created_at),
      discussion_id: Map.get(json, :discussion_id),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      node_id: Map.get(json, :node_id),
      parent_id: Map.get(json, :parent_id),
      reactions: Map.get(json, :reactions),
      repository_url: Map.get(json, :repository_url),
      updated_at: Map.get(json, :updated_at),
      user: Map.get(json, :user)
    }
  end

  def from_json(other, _headers), do: other
end
