# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhookPush do
  @moduledoc false
  defstruct [
    :after,
    :base_ref,
    :before,
    :commits,
    :compare,
    :created,
    :deleted,
    :enterprise,
    :forced,
    :head_commit,
    :installation,
    :organization,
    :pusher,
    :ref,
    :repository,
    :sender
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      after: Map.get(json, :after),
      base_ref: Map.get(json, :base_ref),
      before: Map.get(json, :before),
      commits: Map.get(json, :commits),
      compare: Map.get(json, :compare),
      created: Map.get(json, :created),
      deleted: Map.get(json, :deleted),
      enterprise: Noizu.Github.EnterpriseWebhooks.from_json(Map.get(json, :enterprise)),
      forced: Map.get(json, :forced),
      head_commit: Map.get(json, :head_commit),
      installation: Noizu.Github.SimpleInstallation.from_json(Map.get(json, :installation)),
      organization:
        Noizu.Github.OrganizationSimpleWebhooks.from_json(Map.get(json, :organization)),
      pusher: Map.get(json, :pusher),
      ref: Map.get(json, :ref),
      repository: Map.get(json, :repository),
      sender: Noizu.Github.SimpleUser.from_json(Map.get(json, :sender))
    }
  end

  def from_json(other, _headers), do: other
end
