# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhookSecretScanningScanCompleted do
  @moduledoc false
  defstruct [
    :action,
    :completed_at,
    :custom_pattern_name,
    :custom_pattern_scope,
    :enterprise,
    :installation,
    :organization,
    :repository,
    :secret_types,
    :sender,
    :source,
    :started_at,
    :type
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      action: Map.get(json, :action),
      completed_at: Map.get(json, :completed_at),
      custom_pattern_name: Map.get(json, :custom_pattern_name),
      custom_pattern_scope: Map.get(json, :custom_pattern_scope),
      enterprise: Noizu.Github.EnterpriseWebhooks.from_json(Map.get(json, :enterprise)),
      installation: Noizu.Github.SimpleInstallation.from_json(Map.get(json, :installation)),
      organization:
        Noizu.Github.OrganizationSimpleWebhooks.from_json(Map.get(json, :organization)),
      repository: Noizu.Github.RepositoryWebhooks.from_json(Map.get(json, :repository)),
      secret_types: Map.get(json, :secret_types),
      sender: Noizu.Github.SimpleUser.from_json(Map.get(json, :sender)),
      source: Map.get(json, :source),
      started_at: Map.get(json, :started_at),
      type: Map.get(json, :type)
    }
  end

  def from_json(other, _headers), do: other
end
