# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhookLabelDeleted do
  @moduledoc false
  defstruct [
    :action,
    :enterprise,
    :installation,
    :label,
    :organization,
    :repository,
    :sender
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      action: Map.get(json, :action),
      enterprise: Noizu.Github.EnterpriseWebhooks.from_json(Map.get(json, :enterprise)),
      installation: Noizu.Github.SimpleInstallation.from_json(Map.get(json, :installation)),
      label: Noizu.Github.WebhooksLabel.from_json(Map.get(json, :label)),
      organization:
        Noizu.Github.OrganizationSimpleWebhooks.from_json(Map.get(json, :organization)),
      repository: Noizu.Github.RepositoryWebhooks.from_json(Map.get(json, :repository)),
      sender: Noizu.Github.SimpleUser.from_json(Map.get(json, :sender))
    }
  end

  def from_json(other, _headers), do: other
end
