# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhooksRule do
  @moduledoc false
  defstruct [
    :admin_enforced,
    :allow_deletions_enforcement_level,
    :allow_force_pushes_enforcement_level,
    :authorized_actor_names,
    :authorized_actors_only,
    :authorized_dismissal_actors_only,
    :create_protected,
    :created_at,
    :dismiss_stale_reviews_on_push,
    :id,
    :ignore_approvals_from_contributors,
    :linear_history_requirement_enforcement_level,
    :lock_allows_fork_sync,
    :lock_branch_enforcement_level,
    :merge_queue_enforcement_level,
    :name,
    :pull_request_reviews_enforcement_level,
    :repository_id,
    :require_code_owner_review,
    :require_last_push_approval,
    :required_approving_review_count,
    :required_conversation_resolution_level,
    :required_deployments_enforcement_level,
    :required_status_checks,
    :required_status_checks_enforcement_level,
    :signature_requirement_enforcement_level,
    :strict_required_status_checks_policy,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      admin_enforced: Map.get(json, :admin_enforced),
      allow_deletions_enforcement_level: Map.get(json, :allow_deletions_enforcement_level),
      allow_force_pushes_enforcement_level: Map.get(json, :allow_force_pushes_enforcement_level),
      authorized_actor_names: Map.get(json, :authorized_actor_names),
      authorized_actors_only: Map.get(json, :authorized_actors_only),
      authorized_dismissal_actors_only: Map.get(json, :authorized_dismissal_actors_only),
      create_protected: Map.get(json, :create_protected),
      created_at: Map.get(json, :created_at),
      dismiss_stale_reviews_on_push: Map.get(json, :dismiss_stale_reviews_on_push),
      id: Map.get(json, :id),
      ignore_approvals_from_contributors: Map.get(json, :ignore_approvals_from_contributors),
      linear_history_requirement_enforcement_level:
        Map.get(json, :linear_history_requirement_enforcement_level),
      lock_allows_fork_sync: Map.get(json, :lock_allows_fork_sync),
      lock_branch_enforcement_level: Map.get(json, :lock_branch_enforcement_level),
      merge_queue_enforcement_level: Map.get(json, :merge_queue_enforcement_level),
      name: Map.get(json, :name),
      pull_request_reviews_enforcement_level:
        Map.get(json, :pull_request_reviews_enforcement_level),
      repository_id: Map.get(json, :repository_id),
      require_code_owner_review: Map.get(json, :require_code_owner_review),
      require_last_push_approval: Map.get(json, :require_last_push_approval),
      required_approving_review_count: Map.get(json, :required_approving_review_count),
      required_conversation_resolution_level:
        Map.get(json, :required_conversation_resolution_level),
      required_deployments_enforcement_level:
        Map.get(json, :required_deployments_enforcement_level),
      required_status_checks: Map.get(json, :required_status_checks),
      required_status_checks_enforcement_level:
        Map.get(json, :required_status_checks_enforcement_level),
      signature_requirement_enforcement_level:
        Map.get(json, :signature_requirement_enforcement_level),
      strict_required_status_checks_policy: Map.get(json, :strict_required_status_checks_policy),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
