# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhookMembershipRemoved do
  @moduledoc false
  defstruct [
    :action,
    :enterprise,
    :installation,
    :member,
    :organization,
    :repository,
    :scope,
    :sender,
    :team
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      action: Map.get(json, :action),
      enterprise: Noizu.Github.EnterpriseWebhooks.from_json(Map.get(json, :enterprise)),
      installation: Noizu.Github.SimpleInstallation.from_json(Map.get(json, :installation)),
      member: Noizu.Github.WebhooksUser.from_json(Map.get(json, :member)),
      organization:
        Noizu.Github.OrganizationSimpleWebhooks.from_json(Map.get(json, :organization)),
      repository: Noizu.Github.RepositoryWebhooks.from_json(Map.get(json, :repository)),
      scope: Map.get(json, :scope),
      sender: Map.get(json, :sender),
      team: Noizu.Github.WebhooksTeam.from_json(Map.get(json, :team))
    }
  end

  def from_json(other, _headers), do: other
end
