# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhooksWorkflowJobRun do
  @moduledoc false
  defstruct [
    :conclusion,
    :created_at,
    :environment,
    :html_url,
    :id,
    :name,
    :status,
    :updated_at
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      conclusion: Map.get(json, :conclusion),
      created_at: Map.get(json, :created_at),
      environment: Map.get(json, :environment),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      status: Map.get(json, :status),
      updated_at: Map.get(json, :updated_at)
    }
  end

  def from_json(other, _headers), do: other
end
