# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhooksProjectColumn do
  @moduledoc false
  defstruct [
    :after_id,
    :cards_url,
    :created_at,
    :id,
    :name,
    :node_id,
    :project_url,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      after_id: Map.get(json, :after_id),
      cards_url: Map.get(json, :cards_url),
      created_at: Map.get(json, :created_at),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      project_url: Map.get(json, :project_url),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
