# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhooksSponsorship do
  @moduledoc false
  defstruct [
    :created_at,
    :maintainer,
    :node_id,
    :privacy_level,
    :sponsor,
    :sponsorable,
    :tier
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      created_at: Map.get(json, :created_at),
      maintainer: Map.get(json, :maintainer),
      node_id: Map.get(json, :node_id),
      privacy_level: Map.get(json, :privacy_level),
      sponsor: Map.get(json, :sponsor),
      sponsorable: Map.get(json, :sponsorable),
      tier: Map.get(json, :tier)
    }
  end

  def from_json(other, _headers), do: other
end
