# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhooksMembership do
  @moduledoc false
  defstruct [
    :direct_membership,
    :enterprise_teams_providing_indirect_membership,
    :organization_url,
    :role,
    :state,
    :url,
    :user
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      direct_membership: Map.get(json, :direct_membership),
      enterprise_teams_providing_indirect_membership:
        Map.get(json, :enterprise_teams_providing_indirect_membership),
      organization_url: Map.get(json, :organization_url),
      role: Map.get(json, :role),
      state: Map.get(json, :state),
      url: Map.get(json, :url),
      user: Map.get(json, :user)
    }
  end

  def from_json(other, _headers), do: other
end
