# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WebhookTeamEdited do
  @moduledoc false
  defstruct [
    :action,
    :changes,
    :enterprise,
    :installation,
    :organization,
    :repository,
    :sender,
    :team
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      action: Map.get(json, :action),
      changes: Map.get(json, :changes),
      enterprise: Noizu.Github.EnterpriseWebhooks.from_json(Map.get(json, :enterprise)),
      installation: Noizu.Github.SimpleInstallation.from_json(Map.get(json, :installation)),
      organization:
        Noizu.Github.OrganizationSimpleWebhooks.from_json(Map.get(json, :organization)),
      repository: Map.get(json, :repository),
      sender: Noizu.Github.SimpleUser.from_json(Map.get(json, :sender)),
      team: Noizu.Github.WebhooksTeam1.from_json(Map.get(json, :team))
    }
  end

  def from_json(other, _headers), do: other
end
