# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.Workflow do
  @moduledoc false
  defstruct [
    :badge_url,
    :created_at,
    :deleted_at,
    :html_url,
    :id,
    :name,
    :node_id,
    :path,
    :state,
    :updated_at,
    :url
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      badge_url: Map.get(json, :badge_url),
      created_at: Map.get(json, :created_at),
      deleted_at: Map.get(json, :deleted_at),
      html_url: Map.get(json, :html_url),
      id: Map.get(json, :id),
      name: Map.get(json, :name),
      node_id: Map.get(json, :node_id),
      path: Map.get(json, :path),
      state: Map.get(json, :state),
      updated_at: Map.get(json, :updated_at),
      url: Map.get(json, :url)
    }
  end

  def from_json(other, _headers), do: other
end
