# Generated by `mix github.gen` from docs/github-api/api.github.com.json.
# Do not edit by hand; re-run the task instead.

defmodule Noizu.Github.WorkflowDispatchResponse do
  @moduledoc false
  defstruct [
    :html_url,
    :run_url,
    :workflow_run_id
  ]

  def from_json(json, headers \\ [])
  def from_json(nil, _headers), do: nil

  def from_json(list, headers) when is_list(list) do
    Enum.map(list, &from_json(&1, headers))
  end

  def from_json(json, _headers) when is_map(json) do
    %__MODULE__{
      html_url: Map.get(json, :html_url),
      run_url: Map.get(json, :run_url),
      workflow_run_id: Map.get(json, :workflow_run_id)
    }
  end

  def from_json(other, _headers), do: other
end
